# Generated by Django 5.0.3 on 2024-03-12 13:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст объявления')),
                ('category', models.SlugField(choices=[(1, 'Tanks'), (2, 'Healers'), (3, 'Damage Dealers'), (4, 'Merchants'), (5, 'Guild masters'), (6, 'Quest givers'), (7, 'Blacksmiths'), (8, 'Tanners'), (9, 'Potions Masters'), (10, 'Spell Masters')], max_length=5, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
