# Generated by Django 5.0.3 on 2024-03-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fan_board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_board.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='privatepage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='response',
            name='accepted_answer',
            field=models.ManyToManyField(related_name='accepted_answer', to=settings.AUTH_USER_MODEL, verbose_name='Принятый ответ'),
        ),
        migrations.AddField(
            model_name='response',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_board.advertisement'),
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ManyToManyField(related_name='answer', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовать ответ'),
        ),
        migrations.AddField(
            model_name='privatepage',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_board.response', verbose_name='Отклик'),
        ),
    ]
